POST localhost:8080/task
Content-Type: application/json

{
  "text": "buy bread",
  "tags": ["buy", "bread"]
}
###

POST localhost:8080/task
Content-Type: application/json

{
"text": "buy milk",
"tags": ["buy", "milk"]
}

###

POST localhost:8080/task
Content-Type: application/json

{
  "text": "wash car",
  "tags": ["car", "washing"]
}

###

POST localhost:8080/task
Content-Type: application/json

{
  "text": "task with no tags",
  "tags": []
}

###

POST localhost:8080/task
Content-Type: application/json

{
  "text": "task with one tag",
  "tags": ["oneTag"]
}
###

POST localhost:8080/task
Content-Type: application/json

{
  "text": "29 dec tag",
  "tags": ["date"]
}


