GET  localhost:8080/task/1
Accept: application/json

###

GET  localhost:8080/task/6
Accept: application/json

###

GET  localhost:8080/task/100
Accept: application/json

###

GET  localhost:8080/task/papa
Accept: application/json

###

GET  localhost:8080/due-date/2023/12/28
Accept: application/json

###

GET  localhost:8080/due-date/2023/12/29
Accept: application/json
###

GET  localhost:8080/due-date/2023/12/32
Accept: application/json