env: "local"
admin:
  login: "jandosss1"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
db:
  host: "ep-wild-bonus-53346710.eu-central-1.aws.neon.tech"
  name: "tasks"
  user: "jandosss1"
